---
title: "atac timecourse analysis"
date: "`r Sys.Date()`"
author: 'Roman E. Reggiardo'
output: html_document
editor_options: 
  chunk_output_type: console
---
# nb_setup
```{r, setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 8, collapse = T)
knitr::opts_chunk$set(message = F)
# here::set_here('/home/rreggiar/')
here::here()
suppressPackageStartupMessages(library(tidyverse))
```
# ggplot theme
```{r}
library(ggplot2)
library(ggthemes)
base_size = 10
ggplot2::theme_set(ggthemes::theme_foundation(base_size = base_size,
                                              base_family = 'Helvetica') + 
                     theme(plot.title = element_text(size = base_size, face = 'bold'),
                           panel.background = element_rect(colour = NA),
                           plot.background = element_rect(colour = NA),
                           panel.border = element_rect(colour = NA), 
                           axis.line = element_line(), 
                           axis.line.x = NULL, 
                           axis.line.y = NULL, 
                           axis.text = element_text(size = rel(0.95)), 
                           axis.text.x = element_text(margin = 
                                                        margin(t = 0.8 * base_size/4)), 
                           axis.text.x.top = element_text(margin = 
                                                            margin(b = 0.8 * base_size/4), 
                                                          vjust = 0), 
                           axis.text.y = element_text(margin = 
                                                        margin(r = 0.5 * base_size/4), 
                                                      hjust = 1),
                           axis.text.y.right = element_text(margin = 
                                                              margin(l = 0.5 * base_size/4), 
                                                            hjust = 0), 
                           axis.ticks = element_line(), 
                           axis.ticks.length = unit(base_size/2.5, "pt"), axis.ticks.length.x = NULL, 
                           axis.ticks.length.x.top = NULL, axis.ticks.length.x.bottom = NULL, 
                           axis.ticks.length.y = NULL, axis.ticks.length.y.left = NULL, 
                           axis.ticks.length.y.right = NULL,
                           strip.text = element_text(size = rel(0.8), face = 'bold'),
                           strip.background = element_blank(),
                           legend.key.size= unit(0.08, "in"),
                           legend.spacing = unit(0, "in"),
                           legend.key = element_rect(colour = NA),
                           legend.title = element_text(face="italic"),
                           legend.text = element_text(face = 'bold'),
                           legend.justification = c("right", "top"),
                           legend.box.just = "right",
                           legend.margin = margin(6, 6, 6, 6),
                           plot.tag = element_text(size = base_size, face = 'bold'),
                           plot.margin=margin(0.04,
                                              0.04,
                                              0.04,
                                              0.04,
                                              unit = "in"),
                           legend.box.spacing = unit(-0.02, 'in'),
                           panel.grid.major = element_blank(),
                           panel.grid.minor = element_blank()
                           )
                   )
txt.mm_to_pts <- function(ratio){ base_size * ratio * (25.4 / 72.27) }
```

# Data
## load and parse
```{r}
# these are hard-coded since the data files are all the same
peak_colnames <- c('peak_id', 'chr', 'start', 'end',
                   'strand', 'score', 'focus', 'anno',
                   'detail', 'distance_tss', 'nearest_prom',
                   'entrez_id', 'nearest_unigene', 'nearest_refseq',
                   'nearest_ensg', 'gene_name', 'gene_alias', 
                   'gene_desc', 'biotype')
# grab all the output directories
data_dirs <- list.dirs(here::here('data'), recursive = F)
# aggregate the output data w/in dirs to a list of DFs
data_agg <- 
  lapply(data_dirs, function(dir) { 
  
    dir_name <- basename(dir)
    
    lfc4_colnames <- c('peak_id', 'chr', 'start', 'end',
                     'strand', 'score', 'focus', 
                     'tot_tags', 'bg_tags', 'foldChange', 'pval')
    
    peak <- 
      vroom::vroom(
        list.files(dir, 
                   pattern = '.peak',
                   full.names = T), col_names = peak_colnames
      )
    
    lfc4 <- 
    vroom::vroom(
      list.files(dir, 
                 pattern = 'LFC4',
                 full.names = T), col_names = lfc4_colnames
      )
    
    # add identifying column and calculate log2FC
    lfc4$foldChange <- as.numeric(lfc4$foldChange)
    lfc4$comparison <- dir_name
    lfc4$log2FoldChange <- log2(lfc4$foldChange)
    

    peak_lfc4 <- merge(peak, lfc4, by = c('peak_id', 'chr', 
                                            'start', 'end', 
                                            'strand'))
    return(peak_lfc4)

   }
)
# remove NULL entries (AvA comparisons)
data_agg_filt <- data_agg[!sapply(data_agg, is.null)]
# bind results into single data frame
atac_data <- do.call('rbind', data_agg_filt)

```

# Feature engineering
## parse out useful variables
```{r}
# make some columns to enable numeric comparisons of time, categorical of context
atac_tidy <- 
  atac_data %>% 
    mutate(enriched_in = str_split_fixed(comparison, pattern = '.vs.', n = 3)[,1],
           compared_to = str_split_fixed(comparison, pattern = '.vs.', n = 3)[,2]) %>% 
    mutate(enriched_time = gsub(str_split_fixed(enriched_in, pattern = '_', n = 2)[,2], 
                                pattern = 'hr', replacement = ''),
           compared_time = gsub(str_split_fixed(compared_to, pattern = '_', n = 2)[,2], 
                                pattern = 'hr', replacement = '')) %>% 
    mutate(enriched_context = str_split_fixed(enriched_in, pattern = '_', n = 2)[,1],
           compared_context = str_split_fixed(compared_to, pattern = '_', n = 2)[,1])
```
##
```{r}

```

# Data viz
## time course
```{r}
atac_tidy %>% 
  group_by(enriched_time, enriched_context, compared_context, biotype) %>% 
  summarize(count = n()) %>% 
  ggplot(aes(enriched_time, count, color = biotype, group = biotype)) + 
  geom_line(alpha = 0.4) +
  geom_point(size = 2) +
  ylab('# enriched peaks') + xlab('time') +
  facet_wrap(~enriched_context+compared_context, ncol = 2)


```

